import React, { useEffect, useRef, useState } from "react";
import { base44 } from "@/api/base44Client";
import GlobalNav from "@/components/GlobalNav";
import MeshyConnectCard from "@/components/meshy/MeshyConnectCard";
import CharacterUpload from "@/components/meshy/CharacterUpload";
import GenerationProgress from "@/components/meshy/GenerationProgress";
import SendToUnity from "@/components/meshy/SendToUnity";
import ResultSummary from "@/components/meshy/ResultSummary";

const POLL_MS = 8000;

// The AI character pipeline: connect Meshy → upload image → generate + auto-rig
// → send the rigged character into the live Unity editor.
export default function CreateCharacter() {
  const [meshyConnected, setMeshyConnected] = useState(false);
  const [job, setJob] = useState(null);
  const [progress, setProgress] = useState(0);
  const [startedAt, setStartedAt] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const pollRef = useRef(null);
  const doneRef = useRef(null);

  const stopPolling = () => {
    if (pollRef.current) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
  };
  useEffect(() => () => stopPolling(), []);

  // Pick up the most recent Meshy job on load, so a refresh (or coming back
  // later) resumes the existing generation instead of starting over.
  useEffect(() => {
    (async () => {
      try {
        const [latest] = await base44.entities.MeshyJob.list("-created_date", 1);
        if (!latest || latest.status === "failed") return;
        setJob(latest);
        setStartedAt(new Date(latest.created_date).getTime());
        if (latest.status !== "complete") {
          pollOnce(latest.id);
          startPolling(latest.id);
        } else {
          setProgress(100);
        }
      } catch (e) {
        console.error(e);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const pollOnce = async (jobId) => {
    try {
      const res = await base44.functions.invoke("meshy_check_job", { job_id: jobId });
      const data = res?.data || res;
      if (data?.job) setJob(data.job);
      if (typeof data?.progress === "number") setProgress(data.progress);
      if (data?.status === "complete" || data?.status === "failed") {
        stopPolling();
        if (data?.status === "complete") {
          setTimeout(() => doneRef.current?.scrollIntoView({ behavior: "smooth" }), 300);
        }
      }
    } catch (e) {
      console.error(e);
    }
  };

  const startPolling = (jobId) => {
    stopPolling();
    pollRef.current = setInterval(() => pollOnce(jobId), POLL_MS);
  };

  const handleGenerate = async (file, name) => {
    if (busy) return;
    setBusy(true);
    setError("");
    setProgress(0);
    setStartedAt(Date.now());
    setJob({ character_name: name, status: "uploading" });
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      const res = await base44.functions.invoke("meshy_start_generation", {
        image_url: file_url,
        character_name: name,
      });
      const data = res?.data || res;
      setJob({
        id: data.job_id,
        character_name: name,
        status: "3d_generating",
        image_url: file_url,
      });
      startPolling(data.job_id);
    } catch (e) {
      setJob(null);
      setError(e?.response?.data?.error || e?.message || "Could not start generation.");
    } finally {
      setBusy(false);
    }
  };

  const handleCancel = async () => {
    stopPolling();
    const id = job?.id;
    setJob(null);
    setProgress(0);
    if (id) {
      try {
        await base44.entities.MeshyJob.delete(id);
      } catch (e) {
        console.error(e);
      }
    }
  };

  const handleReset = () => {
    stopPolling();
    setJob(null);
    setProgress(0);
    setError("");
  };

  const generating = job && job.status !== "complete";
  const complete = job?.status === "complete";

  return (
    <div className="min-h-screen w-full bg-black text-stone-200">
      <GlobalNav />
      <main className="mx-auto w-full max-w-3xl space-y-4 px-4 py-8 md:px-6">
        <header className="mb-2">
          <span className="inline-flex items-center gap-3 text-[11px] font-medium uppercase tracking-[0.28em] text-amber-500/80">
            <span className="h-px w-7 bg-amber-500/40" /> AI Character Pipeline
          </span>
          <h1 className="forge-title mt-3 font-display text-3xl font-bold tracking-[0.04em] text-[#FFF6E0]">
            Create Character
          </h1>
          <p className="mt-2 text-sm leading-relaxed text-stone-400">
            2D image in, fully rigged 3D character out — generated by Meshy AI and placed
            straight into your Unity scene.
          </p>
        </header>

        <MeshyConnectCard onStatus={setMeshyConnected} />

        {!job && (
          <CharacterUpload disabled={!meshyConnected} busy={busy} onGenerate={handleGenerate} />
        )}
        {error && !job && (
          <p className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">
            {error}
          </p>
        )}

        {generating && (
          <GenerationProgress job={job} progress={progress} startedAt={startedAt} onCancel={handleCancel} />
        )}

        {complete && (
          <div ref={doneRef} className="space-y-4">
            <SendToUnity
              job={job}
              onSent={() => setJob((prev) => ({ ...prev, sent_to_unity: true }))}
              onReset={handleReset}
            />
            <ResultSummary job={job} />
          </div>
        )}
      </main>
    </div>
  );
}