// Builds the C# editor script that imports a Meshy-rigged character into the
// user's Unity project. The bridge has NO C# compiler — its `script.create`
// tool writes a .cs file into Assets/LovelaceForge/ and Unity compiles it. So
// this script is self-executing: [InitializeOnLoadMethod] fires right after
// that compile, downloads the FBX + animations, configures the Humanoid rig,
// and places the character in the scene (scale 4x, Y rotation 270° — the
// Kizuna/UFE2 facing-right standard). A SessionState marker keeps it from
// re-running on later domain reloads.

const sanitize = (name) => (name || "").replace(/[^A-Za-z0-9 _-]/g, "").trim() || "Character";

export function buildCharacterImportScript({ characterName, riggedFbxUrl, walkingFbxUrl, runningFbxUrl }) {
  const safeName = sanitize(characterName);
  const alnum = safeName.replace(/[^A-Za-z0-9]/g, "") || "Character";
  // Unique class per send so re-imports of the same character still run.
  const className = `LovelaceImport_${alnum}_${Date.now().toString(36)}`;

  const code = `#if UNITY_EDITOR
using System.IO;
using UnityEngine;
using UnityEditor;

// Auto-generated by Lovelace Forge: imports the Meshy-rigged character
// "${safeName}" and places it in the open scene. Runs ONCE, right after
// Unity compiles this file.
public static class ${className}
{
    const string Marker = "${className}_done";

    [InitializeOnLoadMethod]
    static void Bootstrap()
    {
        if (SessionState.GetBool(Marker, false)) return;
        SessionState.SetBool(Marker, true);
        EditorApplication.delayCall += DoImport;
    }

    static void DoImport()
    {
        string charName = "${safeName}";
        string folder = "Assets/GeneratedCharacters/" + charName;
        if (!Directory.Exists(folder)) Directory.CreateDirectory(folder);

        string fbxPath = folder + "/" + charName + "_Rigged.fbx";
        Download("${riggedFbxUrl || ""}", fbxPath);
        Download("${walkingFbxUrl || ""}", folder + "/" + charName + "_Walk.fbx");
        Download("${runningFbxUrl || ""}", folder + "/" + charName + "_Run.fbx");
        AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);

        // Configure the main model as a Humanoid rig for retargeting.
        var importer = AssetImporter.GetAtPath(fbxPath) as ModelImporter;
        if (importer != null)
        {
            importer.animationType = ModelImporterAnimationType.Humanoid;
            importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
            importer.SaveAndReimport();
        }

        var prefab = AssetDatabase.LoadMainAssetAtPath(fbxPath) as GameObject;
        if (prefab == null)
        {
            Debug.LogError("[Lovelace Forge] Could not load imported character at " + fbxPath);
            return;
        }
        var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
        instance.name = charName;
        instance.transform.position = Vector3.zero;
        instance.transform.localScale = new Vector3(4f, 4f, 4f);
        instance.transform.rotation = Quaternion.Euler(0f, 270f, 0f);
        Selection.activeGameObject = instance;
        if (SceneView.lastActiveSceneView != null) SceneView.lastActiveSceneView.FrameSelected();
        Debug.Log("[Lovelace Forge] Character '" + charName + "' imported, rigged as Humanoid, and placed in the scene.");
    }

    static void Download(string url, string path)
    {
        if (string.IsNullOrEmpty(url) || url == "null") return;
        try
        {
            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
            using (var client = new System.Net.WebClient())
                client.DownloadFile(url, path);
        }
        catch (System.Exception e)
        {
            Debug.LogError("[Lovelace Forge] Download failed for " + url + ": " + e.Message);
        }
    }
}
#endif
`;

  return { className, objectName: safeName, code };
}